---
latitude: 43.78256
longitude: 11.28466
map_zoom: 12
name: Stadium Garden
email: steffan@traveltripper.io
phone_number: 001-111-1111
address:
  street1: 2 Via Volturno
  street2: ''
  state: ''
  city: Florence
  country: 
  zip_code: '50123'
_hotel_id: STA655
_portal_id: required-but-empty
_ttweb_plugins_version: v2
_root_path: http://rtexpress-qa.ttaws.com/rt/.
